name: Automated Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Copy ENV file
        run: cp .env.example .env
      - name: Install dependencies
        run: yarn
      - name: Generate APP_KEY
        run: node ace generate:key
      - name: Execute tests
        run: yarn test
        env:
          DB_CONNECTION: sqlite
          CI: true
